(function(b,d,x){function l(b){for(var a={},c,e,f=0;f<b.length;f++)e=b[f],c=e.r+e.s+e.m,e.c&&(a[c]||(a[c]=[]),a[c].push(b[f]));return a}function t(b){for(var a=1;a<arguments.length;a++){var c=arguments[a];try{if(c.isSupported)return c.send(b)}catch(e){}}}function h(){if(f.length){for(var b=0;b<A.length;b++)A[b]();a._flhs+=1;q();t(l(f.splice(0,f.length)),v,I,E)}H=K=0}function q(){C&&g({k:"chk",f:a._flhs,l:a._lpn,s:"full"},"csm")}function g(e,k,c){c=c||{};!b.ue_furl||0===c.bf&&a.isBF||(e={r:c.r||a.rid,
s:c.s||b.ue_sid,m:c.m||b.ue_mid,mkt:c.mkt||b.ue_mkt,sn:c.sn||b.ue_sn,c:k,d:e,t:c.t||a.d(),cs:c.c&&b.ue_qsl},a._lpn[k]=(a._lpn[k]||0)+1,c.b?t(l([e]),v,E):c.nb?t(l([e]),v,I,E):c.img||O[k]?t(l([e]),E):c.ff?(f.push(e),h()):c.n?(f.push(e),0===L?h():H||(H=d.setTimeout(h,L))):(f.push(e),K||(K=d.setTimeout(h,N))))}function u(b,a,c){M++;M==F&&g({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},d.ue_err_chan||"jserr");(M<F||c&&c.il)&&g(b,a,c)}function D(){if(!P){for(var b=0;b<
k.length;b++)k[b]();for(b=0;b<A.length;b++)A[b]();a._flhs+=1;q();t(l(f.splice(0,f.length)),v,E);P=!0}}var y={};(function(){function b(a){return 10>a?"0"+a:a}function a(b){e.lastIndex=0;return e.test(b)?'"'+b.replace(e,function(b){var a=k[b];return"string"===typeof a?a:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function c(b,e){var m,k,g,l,S=f,p,r=e[b];r&&"object"===typeof r&&"function"===typeof r.toJSON&&(r=r.toJSON(b));"function"===typeof h&&(r=h.call(e,b,r));switch(typeof r){case "string":return a(r);
case "number":return isFinite(r)?String(r):"null";case "boolean":case "null":return String(r);case "object":if(!r)return"null";f+=d;p=[];if("[object Array]"===Object.prototype.toString.apply(r)){l=r.length;for(m=0;m<l;m+=1)p[m]=c(m,r)||"null";g=0===p.length?"[]":f?"[\n"+f+p.join(",\n"+f)+"\n"+S+"]":"["+p.join(",")+"]";f=S;return g}if(h&&"object"===typeof h)for(l=h.length,m=0;m<l;m+=1)"string"===typeof h[m]&&(k=h[m],(g=c(k,r))&&p.push(a(k)+(f?": ":":")+g));else for(k in r)Object.prototype.hasOwnProperty.call(r,
k)&&(g=c(k,r))&&p.push(a(k)+(f?": ":":")+g);g=0===p.length?"{}":f?"{\n"+f+p.join(",\n"+f)+"\n"+S+"}":"{"+p.join(",")+"}";f=S;return g}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(a){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(b){return this.valueOf()});
var e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f,d,k={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},h;"function"!==typeof y.stringify&&(y.stringify=function(b,a,e){var m;d=f="";if("number"===typeof e)for(m=0;m<e;m+=1)d+=" ";else"string"===typeof e&&(d=e);if((h=a)&&"function"!==typeof a&&("object"!==typeof a||"number"!==typeof a.length))throw Error("JSON.stringify");return c("",{"":b})})})();
var z=function(){function b(a,c){if(null==a)return c.push("!n");if("number"===typeof a)return c.push("!"+a);if("string"===typeof a)return"\\"==a[a.length-1]?c.push("'"+a.replace(/'/g,"\\'")+"u005C'"):c.push("'"+a.replace(/'/g,"\\'")+"'");if("boolean"===typeof a)return c.push(a?"!t":"!f");if(a instanceof Array){c.push("*");for(var e=0;e<a.length;e++)b(a[e],c);return c.push(")")}if("object"==typeof a){c.push("(");for(e in a)a.hasOwnProperty(e)&&(c.push(e),b(a[e],c));return c.push(")")}return c.push("!n")}
return{stringify:function(a){var c=[];b(a,c);return c.join("")}}}(),Q=b.ue_qsl||2E3,F=1E3,C=1===window.ue_ddq,n=function(){},G=d.JSON&&d.JSON.stringify||y&&y.stringify,e=z.stringify,a=b.ue||{},z=b.uet||n;(b.uet||n)("bb","ue_frst_v2",{wb:1});var r="//"+b.ue_furl+"/1/batch/1/OE/",f=[],k=[],A=[],P=!1,H,K,L=void 0===b.ue_hpfi?1E3:b.ue_hpfi,N=void 0===b.ue_lpfi?1E4:b.ue_lpfi,O={"scheduled-delivery":1},M=0,I=function(){function e(){if(d.XDomainRequest){var b=new XDomainRequest;b.onerror=n;b.ontimeout=n;
b.onprogress=n;b.onload=n;b.timeout=0;return b}if(d.XMLHttpRequest){b=new XMLHttpRequest;if(!("withCredentials"in b))throw"";return b}if(d.ActiveXObject){for(var a=0;a<h.length&&!b;a++)try{b=new ActiveXObject(h[a]),h=[h[a]]}catch(c){}return b}}function k(c){for(var e=[],f=c[0]||{},d=0;d<c.length;d++){var m={};m[c[d].c]=c[d].d;e.push(m)}return{rid:f.r||a.rid,sid:f.s||b.ue_sid,mid:f.m||b.ue_mid,mkt:f.mkt||b.ue_mkt,sn:f.sn||b.ue_sn,reqs:e}}function c(b){var a=k(b),c=e();if(!c)throw"";c.onerror=function(){for(var a=
0;a<b.length;a++)f.push(b[a]);I.isSupported=!1};c.open("POST",r,!0);c.setRequestHeader&&c.setRequestHeader("Content-type","text/plain");c.send(G(a))}var h="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");return{send:function(b){for(var a in b)b.hasOwnProperty(a)&&b[a].length&&c(b[a])},buildPOSTBodyLog:k,isSupported:!0}}(),E=function(){return{send:function(f){for(var d in f)if(f.hasOwnProperty(d)){for(var c=f[d],k=c,h={},g=void 0,
l=0;l<k.length;l++)g=k[l].c,h[g]||(h[g]=[]),h[g].push(k[l]);var c=c[0]||{},k=c.sn||b.ue_sn,c=r+(c.m||b.ue_mid)+":"+(c.s||b.ue_sid)+":"+(c.r||a.rid)+(k?":"+k:""),k=[],g=c,l=[],q=void 0;for(q in h)if(h.hasOwnProperty(q))for(var n=0;n<h[q].length;n++){var u=h[q][n],t=encodeURIComponent((u.cs?e:G)(u.d));l.push({l:t,t:u.t,p:1,c:q,d:u.cs?"c":"j"})}h=l;l=void 0;q="$";for(u=0;u<h.length;){n=h[u];l!=n.c?(g+=q+n.c+"=",q="&",l=n.c):g+=",";var t=g,z=n.d+":",F=n,g=(F.l.match(".{1,"+(Q-g.length)+"}[^%]{0,2}")||
[])[0]||"";F.l=F.l.substr(g.length);g=t+(z+g+":"+n.t);if(n.l)g+=":"+n.p++ +"_",k.push(g),g=c,q="$",l=0;else if(u++,1!=n.p)for(g+=":"+n.p+"_"+n.p,t=0;t<n.p-1;t++)k[k.length-t-1]+=n.p}k.push(g);c=k;for(k=0;k<c.length;k++)(new Image).src=c[k]}},isSupported:!0}}(),v=function(){return{send:function(b){for(var a in b)if(b.hasOwnProperty(a)){var c=I.buildPOSTBodyLog(b[a]);if(!navigator.sendBeacon(r,G(c)))throw"";}},isSupported:!!navigator.sendBeacon}}();a._fic=E;a._fac=I;a._fbc=v;a._flq=f;a.sid=a.sid||b.ue_sid;
a.mid=a.mid||b.ue_mid;a.furl=a.furl||b.ue_furl;a.sn=a.sn||b.ue_sn;a.isBF=function(){var b=d.performance||d.webkitPerformance,e=x.ue_backdetect&&x.ue_backdetect.ue_back&&document.ue_backdetect.ue_back.value,c=a.bfini;return b&&b.navigation&&2===b.navigation.type||1<c||!c&&1<e}();a._flhs=a._flhs||0;a._lpn=a._lpn||{};try{d.amznJQ&&d.amznJQ.declareAvailable&&d.amznJQ.declareAvailable("forester-client"),d.P&&d.P.register&&d.P.register("forester-client",n)}catch(U){b.ueLogError(U,{logLevel:"WARN"})}(function(){a.log&&
a.log.isStub&&(a.log.replay(function(b,a,c){var e=b[2]||{};e.t=a;e.r=c;e.n=1;u(b[0],b[1],e)}),a.onunload.replay(function(b){k.push(b[0])}),a.onflush.replay(function(b){A.push(b[0])}))})();a.log=u;a.log.reset=function(){M=0};a.onunload=function(b){k.push(b)};a.onflush=function(b){A.push(b)};a.attach("beforeunload",D);a.attach("pagehide",D);z("ld","ue_frst_v2",{wb:1})})(ue_csm,window,document);
(function(b,d){function x(b){if(b)return b.replace(/^\s+|\s+$/g,"")}function l(e,a){if(!e)return{};var d="INFO"===a.logLevel;e.m&&e.m.message&&(e=e.m);var f=a.m||a.message||"",f=e.m&&e.m.message?f+e.m.message:e.m&&e.m.target&&e.m.target.tagName?f+("Error handler invoked by "+e.m.target.tagName+" tag"):e.m?f+e.m:e.message?f+e.message:f+"Unknown error",f={m:f,name:e.name,type:e.type,csm:Q+" "+(e.fromOnError?"onerror":"ueLogError")},k,h,g=0,l;f.logLevel=a.logLevel||u;a.adb&&(f.adb=a.adb);if(k=a.attribution)f.attribution=
""+k;if(!d){f.pageURL=a.pageURL||""+(window.location?window.location.href:"")||"missing";f.f=e.f||e.sourceURL||e.fileName||e.filename||e.m&&e.m.target&&e.m.target.src;f.l=e.l||e.line||e.lineno||e.lineNumber;f.c=e.c?""+e.c:e.c;f.s=[];f.t=b.ue.d();if((d=e.stack||(e.err?e.err.stack:""))&&d.split)for(f.csm+=" stack",k=d.split("\n");g<k.length&&f.s.length<F;)(d=k[g++])&&f.s.push(x(d));else for(f.csm+=" callee",h=t(e.args||arguments,"callee"),k=g=0;h&&g<F;)l=C,h.skipTrace||(d=h.toString())&&d.substr&&(l=
0===k?4*C:l,l=1==k?2*C:l,f.s.push(d.substr(0,l)),k++),h=t(h,"caller"),g++;if(!f.f&&0<f.s.length&&(g=f)&&g.s){var q,d=0<g.s.length?g.s[0]:"";k=1<g.s.length?g.s[1]:"";d&&(q=d.match(G));q&&3==q.length||!k||(q=k.match(n));q&&3==q.length&&(g.f=q[1],g.l=q[2])}}return f}function t(b,a){try{return b[a]}catch(d){}}function h(e,a){if(e){var h=l(e,a),f=window.ue_err?window.ue_err.addContextInfo:null;f&&f(h);b.ue.log(h,a.channel||g,{nb:1});"function"===typeof ue_err.elh&&ue_err.elh(e,a);try{if(!e.fromOnError){var k=
d.console,q=d.JSON,f="Error logged with the Track&Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";if(k){if(q&&q.stringify)try{f+=q.stringify(h)}catch(n){f+="no info provided; converting to string failed"}else f+=h.m;"function"===typeof k.error?k.error(f,h):"function"===typeof k.log&&k.log(f,h)}}}catch(u){}}}function q(e,a){if(e&&!(b.ue_err.ec>b.ue_err.mxe)){b.ue_err.ter.push(e);a=a||{};var d=e.logLevel||a.logLevel;a.logLevel=d;a.attribution=e.attribution||a.attribution;d&&d!==
u&&d!==D&&d!==y&&d!==z||b.ue_err.ec++;d&&d!=u||ue_err.ecf++;h(e,a)}}if(!b.ueLogError||b.ueLogError.isStub){var g=b.ue_err_chan||"jserr",u="FATAL",D="ERROR",y="WARN",z="DOWNGRADED",Q="v5",F=20,C=256,n=/\(?([^\s]*):(\d+):\d+\)?/,G=/.*@(.*):(\d*)/;h.skipTrace=1;l.skipTrace=1;q.skipTrace=1;(function(){if(b.ue_err.erl){var e=b.ue_err.erl.length,a,d;for(a=0;a<e;a++)d=b.ue_err.erl[a],h(d.ex,d.info);ue_err.erl=[]}})();b.ueLogError=q}})(ue_csm,window);
ue_csm.ue.exec(function(b,d){var x=function(){},l=function(){return{send:function(b,l){if(l&&b){var g;if(d.XDomainRequest)g=new XDomainRequest,g.onerror=x,g.ontimeout=x,g.onprogress=x,g.onload=x,g.timeout=0;else if(d.XMLHttpRequest){if(g=new XMLHttpRequest,!("withCredentials"in g))throw"";}else g=void 0;if(!g)throw"";g.open("POST",b,!0);g.setRequestHeader&&g.setRequestHeader("Content-type","text/plain");g.send(l)}},isSupported:!0}}(),t=function(){return{send:function(d,l){if(d&&l)if(navigator.sendBeacon(d,
l))b.ue_sbuimp&&b.ue&&b.ue.ssw&&b.ue.ssw("eelsts","scs");else throw"";},isSupported:b.ue_ssbios?!!navigator.sendBeacon&&!(d.cordova&&d.cordova.platformId&&"ios"==d.cordova.platformId):!!navigator.sendBeacon}}();b.ue._ajx=l;b.ue._sBcn=t},"Transportation-clients")(ue_csm,window);
ue_csm.ue.exec(function(b,d){function x(){for(var b=0;b<arguments.length;b++){var e=arguments[b];try{var k;if(e.isSupported){var g=m.buildPayload(A,f);k=e.send(a,g)}else throw dummyException;return k}catch(h){}}G({m:"All supported clients failed",attribution:"CSMSushiClient_TRANSPORTATION_FAIL",f:"sushi-client.js",logLevel:"ERROR"},d.ue_err_chan||"jserr")}function l(){if(f.length){for(var b=0;b<O.length;b++)O[b]();x(n._sBcn||{},n._ajx||{});f=[];k={};A={};I=E=P=H=0}}function t(){var b=new Date,a=function(b){return 10>
b?"0"+b:b};return Date.prototype.toISOString?b.toISOString():b.getUTCFullYear()+"-"+a(b.getUTCMonth()+1)+"-"+a(b.getUTCDate())+"T"+a(b.getUTCHours())+":"+a(b.getUTCMinutes())+":"+a(b.getUTCSeconds())+"."+String((b.getUTCMilliseconds()/1E3).toFixed(3)).slice(2,5)+"Z"}function h(b){try{return JSON.stringify(b)}catch(a){}return null}function q(b){try{return JSON.parse(b)}catch(a){}return null}function g(a,e,k,g){var q=!1;g=g||{};L++;L==z&&G({m:"Max number of Sushi Logs exceeded",f:"sushi-client.js",
logLevel:"ERROR",attribution:"CSMSushiClient_MAX_CALLS"},d.ue_err_chan||"jserr");var n;if(n=!(L>=z))(n=a&&-1<a.constructor.toString().indexOf("Object")&&e&&-1<e.constructor.toString().indexOf("String")&&k&&-1<k.constructor.toString().indexOf("String"))||K++;n&&(a.producerId=a.producerId||e,a.schemaId=a.schemaId||k,a.timestamp=t(),e=Date.now?Date.now():+new Date,a.messageId=b.ue_id+"-"+e+"-"+L,g&&!g.ssd&&(a.sessionId=a.sessionId||b.ue_sid,a.requestId=a.requestId||b.ue_id,a.obfuscatedMarketplaceId=
a.obfuscatedMarketplaceId||b.ue_mid),(e=h(a))?(e=e.length,(f.length==Q||P+e>F)&&l(),P+=e,a={data:m.compressEvent(a)},f.push(a),(g||{}).n?0===v?l():I||(I=d.setTimeout(l,v)):E||(E=d.setTimeout(l,U)),q=!0):q=!1);!q&&b.ue_int&&console.error("Invalid JS Nexus API call");return q}function u(){if(!M){for(var a=0;a<N.length;a++)N[a]();for(a=0;a<O.length;a++)O[a]();f.length&&(b.ue_sbuimp&&b.ue&&b.ue.ssw&&(a=h({dct:A,evt:f}),b.ue.ssw("eeldata",a),b.ue.ssw("eelsts","unk")),x(n._sBcn||{}));M=!0}}function D(b){N.push(b)}
function y(b){O.push(b)}var z=1E3,Q=499,F=524288,C=function(){},n=b.ue||{},G=n.log||C,e=b.uex||C;(b.uet||C)("bb","ue_sushi_v1",{wb:1});var a=b.ue_surl||"https://unagi-na.amazon.com/1/events/com.amazon.csm.nexusclient.gamma",r=["messageId","timestamp"],f=[],k={},A={},P=0,H=0,K=0,L=0,N=[],O=[],M=!1,I,E,v=void 0===b.ue_hpsi?1E3:b.ue_hpsi,U=void 0===b.ue_lpsi?1E4:b.ue_lpsi,m=function(){function b(a){k[a]||(k[a]="#"+H++,A[k[a]]=a);return k[a]}function a(b){if(b)switch(typeof b){case "number":return!(isNaN(b)||
Infinity===b)&&b.toString().length>("#"+H).length;case "boolean":break;case "string":return b.length>("#"+H).length;default:return!0}return!1}function e(f){if(a(f)){var d=0;f instanceof Array?d=2:f instanceof Function?d=0:f instanceof Object&&(d=1);switch(d){case 0:f=b(f);break;case 2:var g=f;f=[];for(var d=g.length,k=0;k<d;k++)f[k]=e(g[k]);break;case 1:d={};for(g in f)f.hasOwnProperty(g)&&(d[b(g)]=-1==r.indexOf(g)?e(f[g]):f[g]);f=d}}return f}return{compressEvent:e,buildPayload:function(){return h({cs:{dct:A},
events:f})}}}();(function(){if(n.event&&n.event.isStub){if(b.ue_sbuimp&&b.ue&&b.ue.ssw&&b.ue.ssw("eeldata")){var a=q(b.ue.ssw("eeldata").val);a&&a.evt instanceof Array&&a.dct instanceof Object&&(f=a.evt,A=a.dct,f&&A&&((a=(b.ue.ssw("eelsts")||{}).val)&&"unk"===a&&l(),b.ue.ssw("eeldata","{}"),b.ue.ssw("eelsts","unk")))}n.event.replay(function(b){b[3]=b[3]||{};b[3].n=1;g.apply(this,b)});n.onSushiUnload.replay(function(b){D(b[0])});n.onSushiFlush.replay(function(b){y(b[0])})}})();n.attach("beforeunload",
u);n.attach("pagehide",u);n._cmps=m;n.event=g;n.event.reset=function(){L=0};n.onSushiUnload=D;n.onSushiFlush=y;try{d.P&&d.P.register&&d.P.register("sushi-client",C)}catch(J){b.ueLogError(J,{logLevel:"WARN"})}e("ld","ue_sushi_v1",{wb:1})},"Nxs-JS-Client")(ue_csm,window);